export interface RewardDistribution {
  id: string;

  campaignId: string;

  currencyId: string;

  /**
   * Original reward before anything
   * is sent to the Party Fund.
   */
  grossAmount: number;

  /**
   * Percentage of the original reward
   * assigned to the Party Fund.
   *
   * Example:
   * 10 = 10%
   */
  partyFundPercentage: number;

  /**
   * Amount generated by the percentage.
   */
  percentagePartyFundAmount: number;

  /**
   * Any whole-unit remainder that could
   * not be divided evenly.
   *
   * In the current single-character
   * implementation this will normally
   * be zero. It becomes important once
   * multiplayer distribution is added.
   */
  remainderAmount: number;

  /**
   * Total amount actually placed into
   * the Party Fund.
   */
  totalPartyFundAmount: number;

  /**
   * Total amount distributed to
   * characters.
   */
  distributedAmount: number;

  /**
   * Number of characters who received
   * a share of this reward.
   */
  recipientCount: number;

  /**
   * Amount received by each character.
   *
   * Multiplayer will eventually support
   * more detailed per-recipient records.
   */
  amountPerRecipient: number;

  description: string;

  createdAt: string;
}

export interface NewRewardDistribution {
  campaignId: string;

  currencyId: string;

  amount: number;

  partyFundPercentage: number;

  description: string;
}

export interface RewardDistributionResult {
  success: boolean;

  message?: string;

  reward?: RewardDistribution;
}
